/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Chat */
        post: operations["ai_chat_api_ai_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/latest-order-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Order Review */
        get: operations["latest_order_review_api_analysis_latest_order_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/cms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze From Cms */
        post: operations["analyze_from_cms_api_analyze_cms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/cms/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Cms Analysis Job */
        post: operations["start_cms_analysis_job_api_analyze_cms_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/cms/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cms Analysis Job Status */
        get: operations["cms_analysis_job_status_api_analyze_cms_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Cms Analysis */
        delete: operations["cancel_cms_analysis_api_analyze_cms_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/category-corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Category Corrections */
        post: operations["save_category_corrections_api_category_corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/category-corrections/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Category Correction Options */
        get: operations["category_correction_options_api_category_corrections_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Classify Uploads */
        post: operations["classify_uploads_api_classify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corporate-inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Corporate Inventory
         * @description Return today's KST corporate inventory with explicit source statuses.
         */
        get: operations["get_corporate_inventory_api_corporate_inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/download/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_api_download__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchange-rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exchange Rate */
        get: operations["exchange_rate_api_exchange_rate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Get */
        get: operations["health_get_api_health_get"];
        put?: never;
        /** Health */
        post: operations["health_api_health_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/client-performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Client Performance
         * @description Accept only small, anonymous browser timing measurements.
         */
        post: operations["client_performance_api_health_client_performance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Live */
        get: operations["health_live_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/order-logic-v2/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Order Logic V2 */
        post: operations["export_order_logic_v2_api_order_logic_v2_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/order-logic-v2/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Order Logic V2 Job */
        post: operations["start_order_logic_v2_job_api_order_logic_v2_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/order-logic-v2/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order Logic V2 Job Status */
        get: operations["order_logic_v2_job_status_api_order_logic_v2_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Order Logic V2 Job Api */
        delete: operations["cancel_order_logic_v2_job_api_api_order_logic_v2_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/order-logic-v2/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Order Logic V2 */
        get: operations["latest_order_logic_v2_api_order_logic_v2_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/order-logic-v3/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Order Logic V3 Job */
        post: operations["start_order_logic_v3_job_api_order_logic_v3_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/order-logic-v3/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order Logic V3 Job Status */
        get: operations["order_logic_v3_job_status_api_order_logic_v3_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Stop Order Logic V3 Job */
        delete: operations["stop_order_logic_v3_job_api_order_logic_v3_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/order-logic-v3/jobs/{job_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order Logic V3 Result Page */
        get: operations["order_logic_v3_result_page_api_order_logic_v3_jobs__job_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/order-logic-v3/season-factors/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active Order Logic V3 Season Factors */
        get: operations["active_order_logic_v3_season_factors_api_order_logic_v3_season_factors_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/order-logic-v3/season-factors/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Order Logic V3 Season Factor Artifact */
        post: operations["refresh_order_logic_v3_season_factor_artifact_api_order_logic_v3_season_factors_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reference/lead-times": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entity Lead Times
         * @description Return lead-time metadata after account/entity authorization only.
         */
        get: operations["entity_lead_times_api_reference_lead_times_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Report */
        post: operations["export_report_api_reports_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/season-trend/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Season Trend */
        post: operations["analyze_season_trend_api_season_trend_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/season-trend/analyze-api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Season Trend From Api */
        post: operations["analyze_season_trend_from_api_api_season_trend_analyze_api_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/season-trend/analyze-api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Season Trend Api Job */
        post: operations["start_season_trend_api_job_api_season_trend_analyze_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/season-trend/analyze-api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season Trend Api Job Status */
        get: operations["season_trend_api_job_status_api_season_trend_analyze_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Season Trend Api Job */
        delete: operations["cancel_season_trend_api_job_api_season_trend_analyze_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/season-trend/brand-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest Brand Reports
         * @description Return only the bounded aggregates needed by the brand-report screen.
         */
        get: operations["latest_brand_reports_api_season_trend_brand_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/season-trend/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Season Trend */
        get: operations["latest_season_trend_api_season_trend_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/support/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Support Tickets */
        get: operations["list_support_tickets_api_support_tickets_get"];
        put?: never;
        /** Create Support Ticket */
        post: operations["create_support_ticket_api_support_tickets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/support/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Support Ticket */
        patch: operations["update_support_ticket_api_support_tickets__ticket_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiChatRequest */
        AiChatRequest: {
            /**
             * Job Id
             * @description Analysis job id.
             */
            job_id: string;
            /**
             * Question
             * @description Question for the SCM AI assistant.
             */
            question: string;
            /**
             * Token
             * @description Temporary download/access token.
             */
            token: string;
        };
        /** AiChatResponse */
        AiChatResponse: {
            /** Answer */
            answer: string;
            /** Context Summary */
            context_summary: {
                [key: string]: number;
            };
            /** Job Id */
            job_id: string;
            /** Model */
            model: string;
        };
        /** AnalysisJobStartResponse */
        AnalysisJobStartResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
        };
        /** AnalysisJobStatusResponse */
        AnalysisJobStatusResponse: {
            /** Created At */
            created_at: string;
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Updated At */
            updated_at: string;
        } & {
            [key: string]: unknown;
        };
        /** AnalysisResponse */
        AnalysisResponse: {
            /** Download Url */
            download_url: string;
            /** File Mapping */
            file_mapping: {
                [key: string]: unknown;
            };
            /** Ingredient Analysis */
            ingredient_analysis?: unknown | null;
            /** Job Id */
            job_id: string;
            /** Season Analysis */
            season_analysis?: unknown | null;
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Tables */
            tables: {
                [key: string]: unknown;
            };
            /** Uploaded Files */
            uploaded_files: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** ApiErrorDetail */
        ApiErrorDetail: {
            /** Code */
            code: string;
            /**
             * Details
             * @default null
             */
            details: unknown | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
            /** Status */
            status: number;
        };
        /**
         * ApiErrorResponse
         * @description Stable error envelope; ``detail`` remains for older clients.
         */
        ApiErrorResponse: {
            /** Detail */
            detail: string;
            error: components["schemas"]["ApiErrorDetail"];
        };
        /** AuthActionResponse */
        AuthActionResponse: {
            /** Ok */
            ok: boolean;
        };
        /** AuthStatusResponse */
        AuthStatusResponse: {
            /** Account Type */
            account_type: string;
            /** Allowed Entities */
            allowed_entities: string[];
            /** Authenticated */
            authenticated: boolean;
            /** Display Name */
            display_name: string;
            /** Entities */
            entities: {
                [key: string]: unknown;
            }[];
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
            /** Permissions */
            permissions: {
                [key: string]: boolean;
            };
            /** Role */
            role: string;
            /** Username */
            username: string;
        };
        /** Body_analyze_api_analyze_post */
        Body_analyze_api_analyze_post: {
            /**
             * Eur Krw Rate
             * @description Optional fixed EUR/KRW rate for this analysis job.
             */
            eur_krw_rate?: number | null;
            /**
             * Files
             * @description Excel files to upload
             */
            files: string[];
            /**
             * Lead Time Air
             * @description Optional air lead time in days.
             */
            lead_time_air?: number | null;
            /**
             * Lead Time Overrides
             * @description Optional JSON object mapping entity transport codes to lead-time days, for example {"OCEAN": 70, "AIR": 15}.
             */
            lead_time_overrides?: string | null;
            /**
             * Lead Time Rail
             * @description Optional rail lead time in days.
             */
            lead_time_rail?: number | null;
            /**
             * Lead Time Sea
             * @description Optional sea lead time in days.
             */
            lead_time_sea?: number | null;
            /**
             * Lead Time Truck
             * @description Optional truck lead time in days.
             */
            lead_time_truck?: number | null;
            /**
             * Roles
             * @description Optional file roles in the same order as files. Recommended for comparison runs.
             */
            roles?: string[] | null;
            /**
             * Safety Months
             * @description Optional safety stock target in months.
             */
            safety_months?: number | null;
            /**
             * Sku Overstock Threshold Pct
             * @description Optional SKU concentration overstock threshold in percentage points.
             */
            sku_overstock_threshold_pct?: number | null;
            /**
             * Sku Shortage Threshold Pct
             * @description Optional SKU concentration shortage threshold in percentage points.
             */
            sku_shortage_threshold_pct?: number | null;
        };
        /** Body_analyze_season_trend_api_season_trend_analyze_post */
        Body_analyze_season_trend_api_season_trend_analyze_post: {
            /**
             * End Date
             * @description Optional analysis end date in YYYY-MM-DD format.
             */
            end_date?: string | null;
            /**
             * Exclude Partial Months
             * @description Whether to exclude incomplete first/last months from seasonality calculations.
             * @default true
             */
            exclude_partial_months: boolean;
            /**
             * Files
             * @description Season/trend Excel files to upload
             */
            files: string[];
            /**
             * Group By
             * @description Analysis grain. Allowed: month, quarter, year.
             * @default month
             */
            group_by: string;
            /**
             * Include Ingredient
             * @description Whether to include slower ingredient trend tables.
             * @default false
             */
            include_ingredient: boolean;
            /**
             * Lead Time Air
             * @description Optional air lead time in days.
             */
            lead_time_air?: number | null;
            /**
             * Lead Time Rail
             * @description Optional rail lead time in days.
             */
            lead_time_rail?: number | null;
            /**
             * Lead Time Sea
             * @description Optional sea lead time in days.
             */
            lead_time_sea?: number | null;
            /**
             * Lead Time Truck
             * @description Optional truck lead time in days.
             */
            lead_time_truck?: number | null;
            /**
             * Metric
             * @description Analysis metric. Allowed: qty, amount.
             * @default qty
             */
            metric: string;
            /**
             * Roles
             * @description File roles in the same order as files. Allowed: sales_history, prod_list, category_correction.
             */
            roles?: string[] | null;
            /**
             * Start Date
             * @description Optional analysis start date in YYYY-MM-DD format.
             */
            start_date?: string | null;
        };
        /** Body_classify_uploads_api_classify_post */
        Body_classify_uploads_api_classify_post: {
            /**
             * Files
             * @description Excel files to classify
             */
            files: string[];
        };
        /** Body_create_support_ticket_api_support_tickets_post */
        Body_create_support_ticket_api_support_tickets_post: {
            /** Attachment */
            attachment?: string | null;
            /** Category */
            category: string;
            /** Content */
            content: string;
            /** Requester Name */
            requester_name: string;
            /** Requester Team */
            requester_team?: string | null;
            /** Title */
            title: string;
        };
        /** CategoryCorrectionItem */
        CategoryCorrectionItem: {
            /** Brand */
            brand?: string | null;
            /** Category1 */
            category1: string;
            /** Category2 */
            category2: string;
            /** Productcode */
            productCode: string;
            /** Productname */
            productName?: string | null;
        };
        /** CategoryCorrectionOptionsResponse */
        CategoryCorrectionOptionsResponse: {
            /** Category1 */
            category1: string[];
            /** Category2Bycategory1 */
            category2ByCategory1: {
                [key: string]: string[];
            };
        };
        /** CategoryCorrectionRequest */
        CategoryCorrectionRequest: {
            /** Items */
            items: components["schemas"]["CategoryCorrectionItem"][];
        };
        /** CategoryCorrectionSaveResponse */
        CategoryCorrectionSaveResponse: {
            /** Saved Count */
            saved_count: number;
            /** Status */
            status: string;
            /** Total Count */
            total_count: number;
        };
        /** ClassificationCandidateResponse */
        ClassificationCandidateResponse: {
            /** Assigned */
            assigned: boolean;
            /** Columns */
            columns: number;
            /** Detected Columns */
            detected_columns: string[];
            /** Key */
            key: string;
            /** Matched Required Columns */
            matched_required_columns: string[];
            /** Missing Required Columns */
            missing_required_columns: string[];
            /**
             * Role
             * @enum {string}
             */
            role: "eu_stock" | "hq_eu_stock" | "sales_detail" | "hq_to_eu_sales_detail" | "shipping" | "inbound" | "sales_history" | "prod_list" | "category_correction";
            /** Rows */
            rows: number;
            /** Score */
            score: number;
        };
        /** ClassificationItemResponse */
        ClassificationItemResponse: {
            /** Candidates */
            candidates: components["schemas"]["ClassificationCandidateResponse"][];
            /** Columns */
            columns: number;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Detected Columns */
            detected_columns: string[];
            /** Error */
            error: string | null;
            /** Evidence */
            evidence: string[];
            /** Index */
            index: number;
            /** Matched Required Columns */
            matched_required_columns: string[];
            /** Missing Required Columns */
            missing_required_columns: string[];
            /** Original Name */
            original_name: string;
            /** Rows */
            rows: number;
            /** Score */
            score: number | null;
            /** Suggested Key */
            suggested_key: string;
            /** Suggested Role */
            suggested_role: ("eu_stock" | "hq_eu_stock" | "sales_detail" | "hq_to_eu_sales_detail" | "shipping" | "inbound" | "sales_history" | "prod_list" | "category_correction") | "";
        };
        /** ClassificationResponse */
        ClassificationResponse: {
            /** Files */
            files: components["schemas"]["ClassificationItemResponse"][];
            /** Required Roles */
            required_roles: ("eu_stock" | "hq_eu_stock" | "sales_detail" | "hq_to_eu_sales_detail" | "shipping" | "inbound" | "sales_history" | "prod_list" | "category_correction")[];
            /** Status */
            status: string;
        };
        /** CmsAnalyzeRequest */
        CmsAnalyzeRequest: {
            /**
             * As Of
             * @description 분석 기준일(YYYY-MM-DD). 재고의 최근 3개월 판매수량 기준일.
             */
            as_of: string;
            /**
             * Date From
             * @description 판매 내역 조회 시작일. 미지정 시 CMS 기본값.
             */
            date_from?: string | null;
            /**
             * Eur Krw Rate
             * @description 고정 EUR/KRW 환율(선택).
             */
            eur_krw_rate?: number | null;
            /** Lead Time Air */
            lead_time_air?: number | null;
            /** Lead Time Overrides */
            lead_time_overrides?: {
                [key: string]: number;
            } | null;
            /** Lead Time Rail */
            lead_time_rail?: number | null;
            /** Lead Time Sea */
            lead_time_sea?: number | null;
            /** Lead Time Truck */
            lead_time_truck?: number | null;
            /** Safety Months */
            safety_months?: number | null;
            /** Sku Overstock Threshold Pct */
            sku_overstock_threshold_pct?: number | null;
            /** Sku Shortage Threshold Pct */
            sku_shortage_threshold_pct?: number | null;
        };
        /** ExchangeRateResponse */
        ExchangeRateResponse: {
            /**
             * Currency Code
             * @default EUR
             * @enum {string}
             */
            currency_code: "EUR" | "USD";
            /** Currency Krw Rate */
            currency_krw_rate: number;
            /** Eur Krw Rate */
            eur_krw_rate: number;
            /** Fallback Rate */
            fallback_rate?: number | null;
            /** Fallback Rate Age Days */
            fallback_rate_age_days?: number | null;
            /** Fallback Rate As Of */
            fallback_rate_as_of?: string | null;
            /** Fallback Rate Source */
            fallback_rate_source?: string | null;
            /** Rate Date */
            rate_date: string;
            /**
             * Rate Source
             * @enum {string}
             */
            rate_source: "api" | "default";
            /** Rate Warning */
            rate_warning?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Analysis */
            analysis: {
                [key: string]: unknown;
            };
            /** Disk */
            disk: {
                [key: string]: number;
            };
            /** Limits */
            limits: {
                [key: string]: number;
            };
            /** Monitoring */
            monitoring: {
                [key: string]: string;
            };
            /** Object Storage */
            object_storage: {
                [key: string]: string;
            };
            /** Redis */
            redis: {
                [key: string]: string;
            };
            /** Reports */
            reports: {
                [key: string]: number;
            };
            /** Requests */
            requests: {
                [key: string]: unknown;
            };
            /** Retention */
            retention: {
                [key: string]: number;
            };
            /** Service */
            service: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Storage */
            storage: {
                [key: string]: components["schemas"]["StorageDirectoryStatus"];
            };
            /** System */
            system: {
                [key: string]: unknown;
            };
            /** Timestamp */
            timestamp: string;
        };
        /** LivenessResponse */
        LivenessResponse: {
            /** Service */
            service: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Timestamp */
            timestamp: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Id */
            id: string;
            /** Password */
            password: string;
        };
        /** OrderLogicV2DecisionOverride */
        OrderLogicV2DecisionOverride: {
            /** Confirmed Qty */
            confirmed_qty: number;
            /** Memo */
            memo?: string | null;
            /** Sku Code */
            sku_code: string;
        };
        /** OrderLogicV2ExportRequest */
        OrderLogicV2ExportRequest: {
            /**
             * Export Mode
             * @enum {string}
             */
            export_mode: "CASH" | "SHORTAGE";
            /** Job Id */
            job_id: string;
            /** Overrides */
            overrides?: components["schemas"]["OrderLogicV2DecisionOverride"][];
            /** Row Ids */
            row_ids?: string[] | null;
        };
        /** OrderLogicV2JobRequest */
        OrderLogicV2JobRequest: {
            /**
             * Applied Mode
             * @enum {string}
             */
            applied_mode: "CASH" | "SHORTAGE";
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Preview
             * @default false
             */
            preview: boolean;
            settings?: components["schemas"]["OrderLogicV2Settings"];
        };
        /** OrderLogicV2JobStartResponse */
        OrderLogicV2JobStartResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @constant
             */
            status: "queued";
        };
        /**
         * OrderLogicV2Settings
         * @description Per-run immutable policy snapshot; defaults match the approved spec.
         */
        OrderLogicV2Settings: {
            /**
             * Cover Weeks
             * @default 4
             */
            cover_weeks: number;
            /**
             * Grade Cutoff
             * @default 0.8
             */
            grade_cutoff: number;
            /**
             * Lt Air Days
             * @default 16.4
             */
            lt_air_days: number;
            /**
             * Lt Rail Days
             * @default 36.6
             */
            lt_rail_days: number;
            /**
             * Lt Sea Days
             * @default 72.9
             */
            lt_sea_days: number;
            /**
             * Sigma L Air Weeks
             * @default 0.68
             */
            sigma_l_air_weeks: number;
            /**
             * Sigma L Rail Weeks
             * @default 1.15
             */
            sigma_l_rail_weeks: number;
            /**
             * Sigma L Sea Weeks
             * @default 2.18
             */
            sigma_l_sea_weeks: number;
            /**
             * Ss Cap Weeks
             * @default 13
             */
            ss_cap_weeks: number;
            /**
             * Ss Floor Weeks
             * @default 2
             */
            ss_floor_weeks: number;
            /**
             * Z Cash Major
             * @default 1.28
             */
            z_cash_major: number;
            /**
             * Z Cash Minor
             * @default 1.08
             */
            z_cash_minor: number;
            /**
             * Z Shortage Major
             * @default 1.68
             */
            z_shortage_major: number;
            /**
             * Z Shortage Minor
             * @default 1.28
             */
            z_shortage_minor: number;
        };
        /**
         * OrderLogicV3JobRequest
         * @description Start one non-operational V3 textbook calculation run.
         */
        OrderLogicV3JobRequest: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Force Refresh
             * @default false
             */
            force_refresh: boolean;
            /**
             * Preview
             * @default true
             * @constant
             */
            preview: true;
        };
        /** OrderLogicV3JobStartResponse */
        OrderLogicV3JobStartResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @constant
             */
            status: "queued";
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Checks */
            checks: {
                [key: string]: string;
            };
            /** Service */
            service: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Timestamp */
            timestamp: string;
        };
        /** ReportBlockRequest */
        ReportBlockRequest: {
            /** Htmlsnapshot */
            htmlSnapshot?: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind?: ("kpi" | "share" | "ranking" | "trend" | "matrix") | null;
            /**
             * Meta
             * @default
             */
            meta: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /** Section */
            section?: ("summary" | "region" | "brand" | "sku" | "cross" | "season" | "ingredient") | null;
            /** Size */
            size?: ("full" | "half") | null;
            /** Snapshot */
            snapshot?: {
                [key: string]: unknown;
            } | null;
            /**
             * Subtitle
             * @default
             */
            subtitle: string;
            /** Title */
            title: string;
            /**
             * Type
             * @default summary
             */
            type: string;
        };
        /** ReportExportRequest */
        ReportExportRequest: {
            /**
             * Audience
             * @default partner
             * @enum {string}
             */
            audience: "internal" | "partner" | "sales";
            /** Blocks */
            blocks?: components["schemas"]["ReportBlockRequest"][];
            /**
             * Format
             * @default ppt
             * @enum {string}
             */
            format: "ppt" | "pdf" | "html" | "xlsx";
            /** Title */
            title?: string | null;
        };
        /** SeasonTrendApiAnalyzeRequest */
        SeasonTrendApiAnalyzeRequest: {
            /** End Date */
            end_date: string;
            /**
             * Exclude Partial Months
             * @default true
             */
            exclude_partial_months: boolean;
            /**
             * Group By
             * @default month
             */
            group_by: string;
            /**
             * Include Ingredient
             * @default true
             */
            include_ingredient: boolean;
            /** Lead Time Air */
            lead_time_air?: number | null;
            /** Lead Time Rail */
            lead_time_rail?: number | null;
            /** Lead Time Sea */
            lead_time_sea?: number | null;
            /** Lead Time Truck */
            lead_time_truck?: number | null;
            /**
             * Metric
             * @default qty
             */
            metric: string;
            /** Start Date */
            start_date: string;
            /** Warehouse */
            warehouse?: string | null;
        };
        /** SeasonTrendApiJobStartResponse */
        SeasonTrendApiJobStartResponse: {
            /** Job Id */
            job_id?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
        };
        /** StorageDirectoryStatus */
        StorageDirectoryStatus: {
            /** Exists */
            exists: boolean;
            /** Path */
            path: string;
            /** Writable */
            writable: boolean;
        };
        /** SupportAttachmentResponse */
        SupportAttachmentResponse: {
            /** Content Type */
            content_type: string | null;
            /** Id */
            id: string;
            /** Original Name */
            original_name: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** SupportTicketListResponse */
        SupportTicketListResponse: {
            /** Items */
            items: components["schemas"]["SupportTicketResponse"][];
            summary: components["schemas"]["SupportTicketSummary"];
        };
        /** SupportTicketResponse */
        SupportTicketResponse: {
            /** Assignee */
            assignee: string | null;
            /** Attachments */
            attachments?: components["schemas"]["SupportAttachmentResponse"][];
            /** Category */
            category: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Due Date */
            due_date: string | null;
            /** Id */
            id: string;
            /** Requester Name */
            requester_name: string;
            /** Requester Team */
            requester_team: string | null;
            /** Status */
            status: string;
            /** Ticket Number */
            ticket_number: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SupportTicketSummary */
        SupportTicketSummary: {
            /** Completed */
            completed: number;
            /** Delayed */
            delayed: number;
            /** In Progress */
            in_progress: number;
            /** Received */
            received: number;
            /** Total */
            total: number;
        };
        /** SupportTicketUpdateRequest */
        SupportTicketUpdateRequest: {
            /** Assignee */
            assignee?: string | null;
            /**
             * Changed By
             * @default SCM 관리자
             */
            changed_by: string;
            /** Due Date */
            due_date?: string | null;
            /** Note */
            note?: string | null;
            /** Status */
            status?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ai_chat_api_ai_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    latest_order_review_api_analysis_latest_order_review_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_api_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    analyze_from_cms_api_analyze_cms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CmsAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    start_cms_analysis_job_api_analyze_cms_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CmsAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJobStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    cms_analysis_job_status_api_analyze_cms_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    cancel_cms_analysis_api_analyze_cms_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthActionResponse"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusResponse"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    save_category_corrections_api_category_corrections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryCorrectionSaveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    category_correction_options_api_category_corrections_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryCorrectionOptionsResponse"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    classify_uploads_api_classify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_classify_uploads_api_classify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_corporate_inventory_api_corporate_inventory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    download_api_download__job_id__get: {
        parameters: {
            query: {
                token: string;
                scenario?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    exchange_rate_api_exchange_rate_get: {
        parameters: {
            query?: {
                currency?: "EUR" | "USD";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    health_get_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    health_api_health_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    client_performance_api_health_client_performance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    health_live_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    health_ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    export_order_logic_v2_api_order_logic_v2_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderLogicV2ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    start_order_logic_v2_job_api_order_logic_v2_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderLogicV2JobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderLogicV2JobStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    order_logic_v2_job_status_api_order_logic_v2_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    cancel_order_logic_v2_job_api_api_order_logic_v2_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    latest_order_logic_v2_api_order_logic_v2_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    start_order_logic_v3_job_api_order_logic_v3_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderLogicV3JobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderLogicV3JobStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    order_logic_v3_job_status_api_order_logic_v3_jobs__job_id__get: {
        parameters: {
            query?: {
                include_result?: boolean;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    stop_order_logic_v3_job_api_order_logic_v3_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    order_logic_v3_result_page_api_order_logic_v3_jobs__job_id__result_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    active_order_logic_v3_season_factors_api_order_logic_v3_season_factors_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    refresh_order_logic_v3_season_factor_artifact_api_order_logic_v3_season_factors_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    entity_lead_times_api_reference_lead_times_get: {
        parameters: {
            query: {
                entity_code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    export_report_api_reports_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    analyze_season_trend_api_season_trend_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_season_trend_api_season_trend_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    analyze_season_trend_from_api_api_season_trend_analyze_api_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeasonTrendApiAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    start_season_trend_api_job_api_season_trend_analyze_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeasonTrendApiAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonTrendApiJobStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    season_trend_api_job_status_api_season_trend_analyze_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    cancel_season_trend_api_job_api_season_trend_analyze_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    latest_brand_reports_api_season_trend_brand_reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    latest_season_trend_api_season_trend_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_support_tickets_api_support_tickets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportTicketListResponse"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    create_support_ticket_api_support_tickets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_support_ticket_api_support_tickets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportTicketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    update_support_ticket_api_support_tickets__ticket_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupportTicketUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportTicketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Standard API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
