from __future__ import annotations

import argparse
import math
import subprocess
import sys
from pathlib import Path
from typing import Any

import requests


DEFAULT_BASE_URL = "http://127.0.0.1:8000"
DEFAULT_OUTPUT_DIR = Path("outputs") / "fastapi_compare"
REQUEST_TIMEOUT_SECONDS = 120
CONTENT_TYPES = {
    ".xls": "application/vnd.ms-excel",
    ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ".xlsm": "application/vnd.ms-excel.sheet.macroEnabled.12",
}
ROLE_ARGUMENTS = (
    ("eu_stock", "eu_stock", "EU local stock file."),
    ("hq_eu_stock", "hq_eu_stock", "HQ EU stock file."),
    ("sales_detail", "sales_detail", "Sales detail file."),
    ("hq_to_eu_sales_detail", "hq_to_eu_sales_detail", "HQ to EU sales detail file."),
    ("shipping", "shipping", "Shipping/container file."),
    ("inbound", "inbound", "Inbound/open PO file."),
)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Upload input files to FastAPI, download the output Excel, and compare it with a Streamlit baseline.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Recommended role-based mode:\n"
            "  python tools/run_fastapi_compare.py --streamlit-output baseline.xlsx "
            "--eu-stock eu.xlsx --hq-eu-stock hq.xlsx --sales-detail sales.xls "
            "--hq-to-eu-sales-detail hq_sales.xls --shipping shipping.xls --inbound inbound.xls "
            "--eur-krw-rate 1746.69\n\n"
            "Fallback auto-classification mode:\n"
            "  python tools/run_fastapi_compare.py --streamlit-output baseline.xlsx --input-files *.xls"
        ),
    )
    parser.add_argument(
        "--streamlit-output",
        required=True,
        type=Path,
        help="Baseline Excel output generated by Streamlit.",
    )
    parser.add_argument(
        "--input-files",
        nargs="+",
        type=Path,
        help="Fallback mode: Excel input files uploaded without roles. Auto-classification is used; role-specific options are recommended.",
    )
    parser.add_argument("--eu-stock", type=Path, help="Role-based upload: eu_stock.")
    parser.add_argument("--hq-eu-stock", type=Path, help="Role-based upload: hq_eu_stock.")
    parser.add_argument("--sales-detail", type=Path, help="Role-based upload: sales_detail.")
    parser.add_argument("--hq-to-eu-sales-detail", type=Path, help="Role-based upload: hq_to_eu_sales_detail.")
    parser.add_argument("--shipping", type=Path, help="Role-based upload: shipping.")
    parser.add_argument("--inbound", type=Path, help="Role-based upload: inbound/open PO.")
    parser.add_argument(
        "--eur-krw-rate",
        type=float,
        help="Optional fixed EUR/KRW rate to send to /api/analyze. Use this for Streamlit/FastAPI parity checks.",
    )
    parser.add_argument(
        "--base-url",
        default=DEFAULT_BASE_URL,
        help=f"FastAPI server base URL. Default: {DEFAULT_BASE_URL}",
    )
    parser.add_argument(
        "--output-dir",
        default=DEFAULT_OUTPUT_DIR,
        type=Path,
        help=f"Directory for downloaded FastAPI output and compare report. Default: {DEFAULT_OUTPUT_DIR}",
    )
    return parser.parse_args(argv)


def collect_upload_plan(args: argparse.Namespace) -> tuple[list[Path], list[str] | None, str]:
    role_inputs = [
        (role, getattr(args, attr))
        for role, attr, _ in ROLE_ARGUMENTS
        if getattr(args, attr) is not None
    ]

    if role_inputs and args.input_files:
        raise RuntimeError("Use either role-specific options or --input-files, not both.")

    if role_inputs:
        roles = [role for role, _ in role_inputs]
        files = [path for _, path in role_inputs]
        return files, roles, "explicit roles"

    if args.input_files:
        return args.input_files, None, "auto-classification fallback"

    raise RuntimeError("No input files provided. Use role-specific options or --input-files.")


def validate_eur_krw_rate(eur_krw_rate: float | None) -> float | None:
    if eur_krw_rate is None:
        return None
    rate = float(eur_krw_rate)
    if not math.isfinite(rate) or rate <= 0:
        raise RuntimeError("--eur-krw-rate must be a positive number.")
    return rate


def validate_paths(streamlit_output: Path, input_files: list[Path]) -> tuple[Path, list[Path]]:
    streamlit_path = streamlit_output.resolve()
    if not streamlit_path.is_file():
        raise FileNotFoundError(f"Streamlit baseline file not found: {streamlit_path}")

    resolved_inputs: list[Path] = []
    for input_file in input_files:
        path = input_file.resolve()
        if not path.is_file():
            raise FileNotFoundError(f"Input file not found: {path}")
        resolved_inputs.append(path)

    return streamlit_path, resolved_inputs


def health_check(base_url: str) -> None:
    url = f"{base_url.rstrip('/')}/api/health"
    try:
        response = requests.post(url, timeout=10)
        response.raise_for_status()
    except requests.exceptions.ConnectionError as exc:
        raise RuntimeError(
            "FastAPI server is not reachable. Start it first:\n"
            "  uvicorn backend.main:app --reload --port 8000"
        ) from exc
    except requests.exceptions.RequestException as exc:
        raise RuntimeError(f"FastAPI health check failed at {url}: {exc}") from exc


def upload_inputs(
    base_url: str,
    input_files: list[Path],
    roles: list[str] | None,
    eur_krw_rate: float | None,
) -> dict[str, Any]:
    url = f"{base_url.rstrip('/')}/api/analyze"
    handles = []
    form_data = [("roles", role) for role in roles] if roles else []
    if eur_krw_rate is not None:
        form_data.append(("eur_krw_rate", str(eur_krw_rate)))
    try:
        for path in input_files:
            handles.append(
                (
                    "files",
                    (
                        path.name,
                        path.open("rb"),
                        CONTENT_TYPES.get(path.suffix.lower(), "application/octet-stream"),
                    ),
                )
            )

        response = requests.post(url, files=handles, data=form_data, timeout=REQUEST_TIMEOUT_SECONDS)
    except requests.exceptions.ConnectionError as exc:
        raise RuntimeError(
            "FastAPI server is not reachable. Start it first:\n"
            "  uvicorn backend.main:app --reload --port 8000"
        ) from exc
    except requests.exceptions.RequestException as exc:
        raise RuntimeError(f"FastAPI analyze request failed: {exc}") from exc
    finally:
        for _, (_, file_obj, _) in handles:
            file_obj.close()

    if response.status_code >= 400:
        detail = ""
        try:
            detail = str(response.json().get("detail", ""))
        except Exception:
            detail = response.text
        raise RuntimeError(f"FastAPI analyze failed with HTTP {response.status_code}: {detail}")

    return response.json()


def print_file_mapping(analyze_result: dict[str, Any]) -> None:
    file_mapping = analyze_result.get("file_mapping")
    if not isinstance(file_mapping, dict) or not file_mapping:
        print("File mapping: (not returned)")
        return

    print("File mapping:")
    for role, filename in file_mapping.items():
        print(f"  {role}: {filename}")


def print_rate_settings(analyze_result: dict[str, Any]) -> None:
    settings = analyze_result.get("settings")
    if not isinstance(settings, dict) or "eur_krw_rate" not in settings:
        print("Using EUR/KRW rate: (not returned)")
        return

    rate = settings.get("eur_krw_rate")
    source = settings.get("rate_source", "unknown")
    rate_date = settings.get("rate_date")
    suffix = f" ({source})"
    if rate_date:
        suffix = f" ({source}, {rate_date})"
    print(f"Using EUR/KRW rate: {rate}{suffix}")


def filename_from_response(download_url: str, job_id: str) -> str:
    name = Path(download_url).name
    if name and "." in name:
        return name
    return f"ESM_order_review_{job_id}.xlsx"


def download_output(base_url: str, download_url: str, job_id: str, output_dir: Path) -> Path:
    if download_url.startswith("http://") or download_url.startswith("https://"):
        url = download_url
    else:
        url = f"{base_url.rstrip('/')}/{download_url.lstrip('/')}"

    job_dir = output_dir.resolve() / job_id
    job_dir.mkdir(parents=True, exist_ok=True)
    output_path = job_dir / filename_from_response(download_url, job_id)

    try:
        response = requests.get(url, timeout=REQUEST_TIMEOUT_SECONDS)
        response.raise_for_status()
    except requests.exceptions.ConnectionError as exc:
        raise RuntimeError(
            "FastAPI server is not reachable while downloading the output. "
            "Check that uvicorn is still running."
        ) from exc
    except requests.exceptions.RequestException as exc:
        raise RuntimeError(f"FastAPI download failed at {url}: {exc}") from exc

    output_path.write_bytes(response.content)
    return output_path


def run_compare(streamlit_output: Path, fastapi_output: Path, report_path: Path) -> int:
    compare_script = Path(__file__).resolve().parent / "compare_streamlit_fastapi_outputs.py"
    command = [
        sys.executable,
        str(compare_script),
        str(streamlit_output),
        str(fastapi_output),
        "--report",
        str(report_path),
    ]
    completed = subprocess.run(command, text=True)
    return completed.returncode


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    base_url = args.base_url.rstrip("/")

    try:
        input_files_arg, roles, upload_mode = collect_upload_plan(args)
        eur_krw_rate = validate_eur_krw_rate(args.eur_krw_rate)
        streamlit_output, input_files = validate_paths(args.streamlit_output, input_files_arg)
        print(f"FastAPI server: {base_url}")
        print(f"Upload mode: {upload_mode}")
        if eur_krw_rate is not None:
            print(f"Requested EUR/KRW rate: {eur_krw_rate}")
        if roles:
            print("Requested roles:")
            for role, path in zip(roles, input_files):
                print(f"  {role}: {path.name}")
        print("Checking FastAPI health...")
        health_check(base_url)

        print(f"Uploading {len(input_files)} file(s) to /api/analyze...")
        analyze_result = upload_inputs(base_url, input_files, roles, eur_krw_rate)
        job_id = str(analyze_result.get("job_id") or "").strip()
        download_url = str(analyze_result.get("download_url") or "").strip()
        if not job_id or not download_url:
            raise RuntimeError(f"Unexpected analyze response: {analyze_result}")

        print(f"Analyze status: {analyze_result.get('status')}")
        print(f"Job ID: {job_id}")
        if "summary" in analyze_result:
            print(f"Summary: {analyze_result['summary']}")
        print_rate_settings(analyze_result)
        print_file_mapping(analyze_result)

        print("Downloading FastAPI output Excel...")
        fastapi_output = download_output(base_url, download_url, job_id, args.output_dir)
        report_path = fastapi_output.parent / "compare_streamlit_fastapi_report.xlsx"

        print(f"FastAPI output: {fastapi_output}")
        print("Running Streamlit vs FastAPI comparison...")
        compare_code = run_compare(streamlit_output, fastapi_output, report_path)

        print(f"Compare report: {report_path}")
        print(f"RESULT: {'PASS' if compare_code == 0 else 'FAIL'}")
        return compare_code
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
